### PR TITLE
Close #65 check youtube links

### LINKED ISSUE #65: YouTube embed code needs updating
More often than not, YouTube source video URL's are copied directly from the browser URL field, rather than from the **"share" -> "embed"** area. This means we always have to adjust the iframe source from `https://.../watch?...` to `https://.../embed/...`.

IMO this should be automated...

Also, be wary of more complicated URL's like those that specify *playlists*.

### PR DESCRIPTION
**Pull request by arolos**

### CODE REVIEW

**Review by kphunter — APPROVED** [review]
Looks good! That makes life a little easier! Thanks.

**Comment by arolos** [comment]
@MCTaylor17 Then they would have to specified that since the code will get rid of everything after the first `&`. Some of the instructor also gave us a youtube video that's a part of a list which can't be embeded to the page.

**Comment by MCTaylor17** [comment]
Have a look at this:

https://stackoverflow.com/questions/18804904/retrieve-all-videos-from-youtube-playlist-using-youtube-v3-api

As for the queries, when you split on the `&` Take array[1] and append it to the finished URL ;)

**Comment by MCTaylor17** [comment]
Once you have a list of videos, you could populate them into a #slider.

**Pull request merged**
