### PR TITLE
Change class image to img

### LINKED ISSUE #72: Change class image to img
We need to change this class name because tinyMCE is using the same class name.

### PR DESCRIPTION
**Pull request by arolos**
Closes #72

### CODE REVIEW

**Comment by MCTaylor17** [comment]
I would advise against merging this until your next major version upgrade.

**Comment by MCTaylor17** [comment]
There might be a workaround using an `@media` rule or applying styles with JavaScript which doesn't run in the WYSIWYG.

**Comment by arolos** [comment]
@MCTaylor17 The problem is tinyMCE is using `figure.image` in their class name and javascript code. With figure class `image`, if you try to replace it in the editor, it will insert a new image at the bottom of the page.

**Comment by MCTaylor17** [comment]
It sounds like the problem goes beyond simple CSS conflicts and into JS conflicts, although I'm basing this on a very short text description of a very visual problem...

If you implement this, I would suggest leaving the CSS completely untouched.  Use JS to make it backwards compatible:

```js
$("figure.img").removeClass("img").addClass("image");
```

**Comment by MCTaylor17** [comment]
No comment 😶

**Comment by kphunter** [comment]
This change simply keeps Dewordify in sync with Sugar Suite v1 and the Conversion Guide... And we decided we didn't want this frustration to perpetuate for the indefinite period between now and when we have a v2 ready for production. I will endeavour to remind issue reporters how important it is to fully describe the problem statement...!

**Pull request merged**
