### PR TITLE
Adds swapper marker to markoutMap

### LINKED ISSUE #54: Add swapper
We need to add the new swapper feature to the markout map.

### PR DESCRIPTION
**Pull request by arolos**
Closes #54

### CODE REVIEW

**Comment by MCTaylor17** [comment]
@Arv91 Sorry for the delay.

I believe the tabbing was optimized to create more readable columns of information when viewed in a code editor.  If you auto-beautified this file, @kphunter might be annoyed...

**Comment by MCTaylor17** [comment]
Other mappings might also include:
* slider
* carousel

It's a safe assumption anybody asking for #slider will be happy with a #swapper.

**Comment by arolos** [comment]
@MCTaylor17 Oh, yeah. I added those because it doesn't look good visual studio code and realized the difference after pushing it. I tried the 4 spaces instead of tab and it looks good on github and Visual studio code.

**Comment by MCTaylor17** [comment]
Thanks @Arv91

**Pull request merged**
